/*
 * This file is generated by jOOQ.
*/
package io.jedaev.lomonosov.model.tables.records;


import io.jedaev.lomonosov.model.tables.Securities;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecuritiesRecord extends UpdatableRecordImpl<SecuritiesRecord> implements Record7<Integer, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 98418026;

    /**
     * Setter for <code>public.securities.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.securities.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.securities.secid</code>.
     */
    public void setSecid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.securities.secid</code>.
     */
    public String getSecid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.securities.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.securities.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.securities.shortname</code>.
     */
    public void setShortname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.securities.shortname</code>.
     */
    public String getShortname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.securities.isin</code>.
     */
    public void setIsin(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.securities.isin</code>.
     */
    public String getIsin() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.securities.regnumber</code>.
     */
    public void setRegnumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.securities.regnumber</code>.
     */
    public String getRegnumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.securities.issuesize</code>.
     */
    public void setIssuesize(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.securities.issuesize</code>.
     */
    public Integer getIssuesize() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, String, String, String, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Securities.SECURITIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Securities.SECURITIES.SECID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Securities.SECURITIES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Securities.SECURITIES.SHORTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Securities.SECURITIES.ISIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Securities.SECURITIES.REGNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Securities.SECURITIES.ISSUESIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSecid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getShortname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIsin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getRegnumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getIssuesize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value2(String value) {
        setSecid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value4(String value) {
        setShortname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value5(String value) {
        setIsin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value6(String value) {
        setRegnumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord value7(Integer value) {
        setIssuesize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecuritiesRecord
     */
    public SecuritiesRecord() {
        super(Securities.SECURITIES);
    }

    /**
     * Create a detached, initialised SecuritiesRecord
     */
    public SecuritiesRecord(Integer id, String secid, String name, String shortname, String isin, String regnumber, Integer issuesize) {
        super(Securities.SECURITIES);

        set(0, id);
        set(1, secid);
        set(2, name);
        set(3, shortname);
        set(4, isin);
        set(5, regnumber);
        set(6, issuesize);
    }
}
