spring:
  application:
    name: Lomonosov
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lomonosov
    username: postgres
    password: postgres
  jooq:
    sql-dialect: postgres_9_5
logging:
  level:
    root: warn
    io.pozhidaev.lomonosov: info
lomonosov:
  chrome-bin-path: chrome