/*
 * This file is generated by jOOQ.
*/
package io.jedaev.lomonosov.db;


import io.jedaev.lomonosov.db.tables.Securities;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.securities</code>.
     */
    public static final Securities SECURITIES = io.jedaev.lomonosov.db.tables.Securities.SECURITIES;
}
